import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';
import { getDb } from './db.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');
const productsFile = path.join(rootDir, 'src', 'products-data.js');
const scriptsDir = path.join(rootDir, 'scripts');

export function syncProductsAndRebuild() {
  try {
    const db = getDb();
    
    // Read products
    const productsRows = db.prepare(`SELECT * FROM products ORDER BY sort_order ASC, id ASC`).all();
    const products = [];
    
    for (const p of productsRows) {
      const varietiesRows = db.prepare(`SELECT * FROM varieties WHERE product_id = ? ORDER BY sort_order ASC, id ASC`).all(p.id);
      
      const varieties = varietiesRows.map(v => ({
        slug: v.slug,
        name: v.name,
        code: v.code,
        tagline: v.tagline,
        image: v.image,
        desc: v.desc,
        benefits: v.benefits_json ? JSON.parse(v.benefits_json) : [],
        health: v.health_json ? JSON.parse(v.health_json) : [],
        waMsg: v.wa_msg
      }));
      
      products.push({
        id: p.id,
        slug: p.slug,
        name: p.name,
        tagline: p.tagline,
        icon: p.icon,
        image: p.image,
        desc: p.desc,
        specs: p.specs_json ? JSON.parse(p.specs_json) : {},
        benefits: p.benefits_json ? JSON.parse(p.benefits_json) : [],
        health: p.health_json ? JSON.parse(p.health_json) : [],
        waMsg: p.wa_msg,
        tradeType: p.trade_type,
        varieties: varieties
      });
    }
    
    // Construct JS file content
    const fileContent = `// Auto-generated by backend sync\n\nexport const products = ${JSON.stringify(products, null, 2)};\n`;
    
    fs.writeFileSync(productsFile, fileContent, 'utf-8');
    
    // Run rebuild script
    if (fs.existsSync(path.join(scriptsDir, 'generate-pages.js'))) {
      execSync('node scripts/generate-pages.js', { cwd: rootDir, stdio: 'inherit' });
    }
    
    return { success: true, message: 'Products synced and static pages rebuilt successfully.' };
  } catch (error) {
    console.error('Error during sync and rebuild:', error);
    return { success: false, message: 'Failed to sync products and rebuild.', error: error.message };
  }
}
